### ISSUE TITLE
misc comments

### ISSUE THREAD

**Issue by timotheecour** [slangmgh/nims#2]
- [ ] use std/compilesettings, instead of redoing what the compiler does, eg:

```
let libs_arg = args.filterIt(it.startsWith("--lib:") or it.startsWith("-lib:"))
```

- [ ] comments in english instead of chinese would make this library more usable by a broader audience
- [ ] looks like some functionality is duplicated from compiler code, consider using `import compiler/foo {.all.}` if you're simply duplicating functionality that is private

**Comment by slangmgh** [comment]
1. Now use parseopt to deal with the command line.
2. Comments is english now.
3. There is no available proc from compiler code, may be similar, but a little different, the compiler is not coded for repl, so there is some nasty tricky code to do something.
