### ISSUE TITLE
Problem with compilation

### ISSUE THREAD

**Issue by not-lum** [slangmgh/nims#3]
I tried to compile your program on Windows with `nim c -d:release -d:nimcore nims.nim`, but an error appeared:
![image](https://user-images.githubusercontent.com/62594565/121568621-8c859780-ca28-11eb-8e93-b53f4e34e529.png)
My Nim version is 1.4.8

**Comment by slangmgh** [comment]
You can just comment the error line or using the most recent devel version of the compiler.
