### ISSUE TITLE
No outputs or errors when running this on Linux

### ISSUE THREAD

**Issue by kaushalmodi** [slangmgh/nims#4]
Hello,

I built this project using `nim c -d:release -d:nimcore nims.nim` on CentOS 7.6.

It compiled fine and it even runs when I type `./nims`. But given any input at the prompt, it doesn't output anything.

For reference, here's how the outputs work in `nim secret`:

![image](https://user-images.githubusercontent.com/3578197/121585254-5b916c80-ca00-11eb-8eb6-a209d0638213.png)

And here's what I see with `nims`:

![image](https://user-images.githubusercontent.com/3578197/121585281-651ad480-ca00-11eb-8e16-b73ec6c7bc30.png)

**Comment by kaushalmodi** [comment]
I think something low-level is broken. Quickly glancing at the code, I think `help`, `exit` should work, but they are not.

![image](https://user-images.githubusercontent.com/3578197/121589575-39e6b400-ca05-11eb-8cdd-54a139b276bf.png)

Also, does that strange numbering in the prompt give any clue? 1 > 4 > 5 > 6 > 3 > 4 ??

**Comment by kaushalmodi** [comment]
I rebuilt `nims` today using https://github.com/slangmgh/nims/commit/5ae6d2bfbb227a1e5e8ac4f155fdad2fbfd513e2 and it's still not working:

![image](https://user-images.githubusercontent.com/3578197/121737839-682cc800-cac7-11eb-9091-006a10ee8d92.png)

**Comment by slangmgh** [comment]
Please try the newest code.
Or wait till I setup linux enviroment.

**Comment by shirleyquirk** [comment]
same here, except infinite loop when `Error: EOF reached`.

the issue is that `is_paste` is always true.  
i really dont think timing is a robust way to detect a paste.

**Comment by slangmgh** [comment]
I think it's the problem of redirect output, now I have updated the code and using _dup _dup2 to redirect back to stdout, please check again.

**Comment by slangmgh** [comment]
> same here, except infinite loop when `Error: EOF reached`.
> 
> the issue is that `is_paste` is always true.
> i really dont think timing is a robust way to detect a paste.

I add an option to enable/disable it.

**Comment by shirleyquirk** [comment]
hey, great work, now works (after i change `findNimStdLib` to `findNimStdLibCompileTime`)

I can even get pasting to work, but here's the subtle brokenness:
```
1>>> echo "works great"
works great
1>>> echo "still 1>>>??"
still 1>>>??
1>>> #but after a comment
1>>> echo "it increments but wont print"
2>>> echo "ever again"
3>>> for i in 0..3:
4>>>   echo i
5>>> 
6>>> #nothing
7>>> for i in 0..3:
  echo i 8>>> 
9>>>
```

**Comment by slangmgh** [comment]
Yes, paste function is broken.

**Comment by slangmgh** [comment]
Please update the code and try again.

**Comment by shirleyquirk** [comment]
great work.

CTRL-C   works
quit          works
pasting    works 
   It's initially disconcerting to have the "5>++" paste itself to the end of the line, but one quickly learns just to leave things alone and they'll work

CTRL-D   infinite loop
    meh. as long as EOF doesn't get injected from a paste, not a big issue.

I still need to change that `findNimStdLib` to `findNimStdLibCompileTime` to get it to run.

It's useable!  I'll start using it and see what comes up in daily usage.

**Comment by kaushalmodi** [comment]
@slangmgh Thanks for fixing this. I now confirm the fix. I was away from PC for few days and so couldn't reply sooner.
